import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import HeaderLayout from "@/components/HeaderLayout";
import FooterLayout from "@/components/FooterLayout";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import Image from "next/image";

const roboto = Roboto_Slab({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "CGV Cinema",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ReactQueryProvider>
          <HeaderLayout />
          {children}
          <div className="fixed bottom-4 right-4 z-10">
            <Image
              src="/minion-homepage.gif"
              alt="minion-icon"
              height={100}
              width={100}
            />
          </div>
          <FooterLayout />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
